version: 2
project_name: ocyd

before:
  hooks:
    - go mod tidy

builds:
  - id: ocyd
    main: ./cmd/ocyd
    binary: ocyd
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: ocydctl
    main: ./cmd/ocydctl
    binary: ocydctl
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - README.ru.md
      - LICENSE

release:
  prerelease: auto
